# Generated by Django 2.0.4 on 2018-04-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exchange_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='blogspost',
            name='timestamp_s',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
