# Generated by Django 2.0.4 on 2018-04-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180430_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange_record',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='exchange_record',
            name='timestamp_s',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
