# Generated by Django 2.0.4 on 2018-04-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180430_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspost',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
